# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb1e10f1e30aca2c0863377f5eb3000348ca3b7153dd861789d9b355b40aeb65a2ccf9cb776aa98cd1304dac0277fd367c30f9fbea25f9d031660060a32bf37

test:
  secret_key_base: edbf93f6b2db24ae41450c19cdd02eb3cf74ac466131e953c149a8f6458bad70ab8526c1729dae86826ffba562f06af890415e017dabf40fe772d2ec9dd908d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
